# Labels for batch 2 (tokio, axum, quinn, tracing, dropshot).
from batch1 import y, dup, no

T, A, Q, TR, D = "tokio-rs/tokio", "tokio-rs/axum", "quinn-rs/quinn", "tokio-rs/tracing", "oxidecomputer/dropshot"
TI = "https://github.com/tokio-rs/tokio/issues/"

LABELS = [
    (T, 6493, y("single_api", "select", "state_corruption", "yes", "app", "failure", "high",
                "Barrier::wait in select!; generation advanced by cancelled waits")),
    (T, 6494, dup(TI + "6493", "doc fix: Barrier not cancel safe")),
    (T, "5ba12a71451c", dup(TI + "6493", "doc fix commit")),
    (T, 6877, y("single_api", "select", "state_corruption", "yes", "app", "failure", "high",
                "write_all/read_exact in select! loop; partial writes corrupt the byte stream")),
    (T, 5285, y("context", "select", "state_corruption", "yes", "app", "failure", "high",
                "request/response helper under Mutex cancelled by timer mid-protocol; next caller reads stale reply")),
    (T, 5535, y("context", "timeout", "data_loss", "no", "app", "failure", "high",
                "cancelled stdin read keeps running on blocking pool and consumes next terminal event; "
                "zombie operation not modelled by injection")),
    (T, 3711, y("other", "timeout", "resource_leak", "no", "app", "failure", "medium",
                "tokio::fs read on blocking pool outlives timeout; fd stays open (zombie operation)")),
    (T, 2318, y("other", "select", "deadlock", "no", "library", "failure", "medium",
                "unselected stdin read keeps blocking thread; runtime cannot exit (zombie operation)")),
    (T, 7979, y("wrapper", "drop", "resource_leak", "no", "library", "review", "high",
                "io_uring open completes after future dropped; fd owned only by the dropped future",
                "https://github.com/tokio-rs/tokio/pull/7983")),
    (T, 7983, dup(TI + "7979", "fix")),
    (T, 8112, y("other", "drop", "panic", "no", "library", "review", "medium",
                "io_uring late CQEs after cancelled op slot removal")),
    (T, 8260, y("other", "drop", "deadlock", "yes", "library", "review", "high",
                "cancelled reserve_many returns permits without waking receiver -> recv hangs")),
    (T, 2685, y("other", "drop", "resource_leak", "yes", "library", "failure", "high",
                "dropping child future with kill_on_drop leaves zombie process until next poll")),
    (T, 3965, y("other", "abort", "resource_leak", "yes", "library", "failure", "high",
                "cancelled future leaked by runtime; fixes #3964")),
    (T, "634fcac2d9a2", dup("https://github.com/tokio-rs/tokio/pull/3965", "commit")),
    (T, "7c4183a45d35", dup("https://github.com/tokio-rs/tokio/pull/3965", "commit")),
    (T, 3929, y("other", "abort", "other", "yes", "library", "review", "high",
                "abort drops LocalSet task future on the wrong thread (RUSTSEC-2021-0072, unsound)")),
    (TR, 2114, dup(TI + "3929", "RUSTSEC advisory mirror")),
    (T, 3672, y("other", "abort", "panic", "yes", "library", "failure", "high",
                "abort from another thread panics basic_scheduler (#3662)")),
    (T, 2340, y("other", "drop", "other", "yes", "library", "review", "high",
                "dangling pointer when semaphore acquire futures are cancelled during notify (memory safety)")),
    (T, 1842, y("other", "shutdown", "panic", "yes", "library", "failure", "medium",
                "LocalSet drop panics with unfinished futures")),
    (T, 542, y("other", "shutdown", "resource_leak", "unknown", "library", "failure", "medium",
               "futures with pending notification leaked on runtime drop (tokio 0.1)")),
    (T, 8258, y("other", "drop", "other", "unknown", "library", "review", "low",
                "NamedPipeServer drop without CancelIoEx; pending overlapped I/O may write freed memory (PR unmerged)")),
    (T, 5861, dict(relevant="unclear", confidence="medium",
                   notes="task memory retained by waker clones after cancellation; arguably by design")),
    (Q, 1458, y("other", "drop", "resource_leak", "yes", "library", "failure", "high",
                "Stopped future polled then dropped leaks waker registration until connection close")),
    (A, 2705, y("other", "drop", "resource_leak", "yes", "library", "failure", "medium",
                "dropping serve future does not drop open TcpStreams (PR unmerged)")),
    (T, 5404, no("notify_waiters race, not cancellation", "medium")),
    (T, 7462, no("run_until_cancelled polling order; semantics, not a cancellation defect", "medium")),
    (T, 8095, no("hardening against app-side Sender leak", "medium")),
    (T, 8185, no("io_uring submit failure, not cancellation", "medium")),
    (T, 8366, no("io_uring submit failure, not cancellation", "medium")),
    (T, 4296, no("missing flush, not cancellation", "medium")),
    (T, 4862, no("runtime dropped under spawn_blocking; not future cancellation", "low")),
    (T, 5812, no("aliasing hygiene in Notify", "low")),
    (T, 2839, no("watch readiness assertion, not cancellation", "medium")),
    (T, 7425, no("select! pattern/else usage", "low")),
    (T, 4095, no("peek behaviour, unrelated", "low")),
    (T, 6979, no("unrelated unwind", "low")),
    (T, 7144, no("pidfd panic, unrelated", "low")),
    (A, 3326, dict(relevant="unclear", confidence="low", notes="graceful shutdown hang, cause unclear")),
    (A, 3112, no("tokio-console lost-waker warning", "low")),
    (D, 695, no("feature request motivated by omicron#3140", "high")),
    (D, 701, no("feature: detached handlers (mitigation)", "high")),
]
