# Labels for batch 3: "cancel" termset, the 17 repos collected after batch 2 plus grpc-rust.
# Written directly in codebook v2. Rows not listed here but in reviewed_batch3.txt are `no`.
from batch1 import dup, no

MZ, PG, DB, DN = ("MaterializeInc/materialize", "cloudflare/pingora", "databendlabs/databend",
                  "denoland/deno")
GR, LP, LK, MS = "grpc/grpc-rust", "libp2p/rust-libp2p", "linkerd/linkerd2-proxy", "meilisearch/meilisearch"
IR, NE, PK, QD = "n0-computer/iroh", "neondatabase/neon", "paritytech/polkadot-sdk", "qdrant/qdrant"
RD, RW, VE = "redis-rs/redis-rs", "risingwavelabs/risingwave", "vectordotdev/vector"

AUDIT = "structured audit-style report"


def v2(holder, phase, after, violation, outlives, tags, source, layer, found, inj, conf,
       notes="", fix=""):
    return dict(relevant="yes", holder=holder, phase=phase, after=after, violation=violation,
                outlives=outlives, tags=tags, cancel_source=source, layer=layer, found_by=found,
                injectable=inj, confidence=conf, notes=notes, fix_url=fix)


def gh(repo, kind, n):
    return f"https://github.com/{repo}/{kind}/{n}"


def adjacent(notes, conf="medium"):
    return dict(relevant="adjacent", confidence=conf, notes=notes)


def unclear(notes, conf="low"):
    return dict(relevant="unclear", confidence=conf, notes=notes)


LABELS = [
    # ---------------- Materialize ----------------
    (MZ, 28816, v2("dropped_future", "acquired_uncommitted", "retry", "loss;corruption", "no",
                   "wrapper", "select", "app", "review", "yes", "high",
                   "SequentialHydration::recv sends commands via non-cancel-safe GenericClient::send")),
    (MZ, "472d39a82019", dup(gh(MZ, "pull", 28816), "commit")),
    (MZ, "5f02d4fe4120", dup(gh(MZ, "pull", 28816), "merge commit")),
    (MZ, 12479, v2("shared_object", "acquired_uncommitted", "retry", "invariant", "no",
                   "wrapper;context", "select", "app", "review", "yes", "medium",
                   "Controller::recv in select! did cancel-unsafe processing; split into ready/process")),
    (MZ, 29221, v2("dropped_future", "acquired_uncommitted", "none", "liveness", "no", "wrapper",
                   "drop", "app", "failure", "yes", "high",
                   "TimelyContainer taken out of Arc, then await; gRPC disconnect drops it, drop blocks thread forever")),
    (MZ, "85fa1a6013b1", dup(gh(MZ, "pull", 29221), "commit")),
    (MZ, 38577, v2("shared_object", "acquired_uncommitted", "reuse", "panic;invariant", "no",
                   "context", "drop", "app", "review", "yes", "high",
                   "Pending state replaced by placeholder across await; later into_result panics")),
    (MZ, "951d074c8798", dup(gh(MZ, "pull", 38577), "commit")),
    (MZ, 28956, v2("dropped_future", "before_acquire", "retry", "liveness", "no", "context",
                   "select", "app", "review", "yes", "medium",
                   "recreating cancel-safe futures and polling once each time may never make progress")),
    (MZ, "7e19e4be1b29", dup(gh(MZ, "pull", 28956), "commit")),
    (MZ, 12485, v2("shared_object", "acquired_uncommitted", "reuse", "mismatch;panic", "no",
                   "context", "select", "app", "failure", "yes", "medium",
                   "cancel mid-reconnect: sends for old cluster delivered to new one")),
    (MZ, 35938, v2("other_task", "acquired_uncommitted", "retry", "leak", "yes", "other", "drop",
                   "app", "failure", "yes", "high",
                   "dropped tonic Channel, hyper background task keeps HTTP/2 connection open per reconnect")),
    (MZ, 26190, v2("other_task", "acquired_uncommitted", "none", "leak", "yes", "other", "drop",
                   "app", "failure", "yes", "medium",
                   "spawned task outlives dropped dataflow (incident)")),
    (MZ, 34980, adjacent("futurelock (RFD 609) in lease update")),
    (MZ, "b8f9449becda", adjacent("futurelock fix commit (#34980)")),
    (MZ, 10971, unclear("latent select! issue in simple sources; PR unmerged, 'in practice doesn't happen'")),
    (MZ, 12714, unclear("'make simple source cancel safe', no description")),
    # ---------------- Pingora ----------------
    (PG, 932, v2("shared_object", "acquired_uncommitted", "reuse", "loss;invariant", "no", "context",
                 "drop", "library", "review", "yes", "medium",
                 "cancelled cache writer: partial reader reports clean EOF; " + AUDIT)),
    (PG, 934, v2("dropped_future", "acquired_uncommitted", "retry", "panic", "no", "wrapper;context",
                 "timeout", "library", "review", "yes", "medium",
                 "ResponseFuture taken out of session then awaited; timeout drops it; retry panics; " + AUDIT,
                 gh(PG, "pull", 944))),
    (PG, 944, dup(gh(PG, "issues", 934), "fix (closed unmerged)")),
    (PG, 931, v2("dropped_future", "acquired_uncommitted", "none", "liveness;collateral_failure", "no",
                 "wrapper", "drop", "library", "review", "yes", "medium",
                 "coalescing lock released only after await; cancelled writer leaves it; same-key waiters block; "
                 + AUDIT, gh(PG, "pull", 948))),
    (PG, 948, dup(gh(PG, "issues", 931), "fix (open)")),
    (PG, 933, v2("dropped_future", "recorded_undelivered", "retry", "loss", "no", "wrapper;context",
                 "drop", "library", "review", "yes", "medium",
                 "finish() marks Complete before sending Done; cancel drops Done; retry is a no-op; " + AUDIT)),
    (PG, 910, adjacent("stream handles held while not polled (upstream write blocked); no drop")),
    (PG, 911, adjacent("fix for #910")),
    (PG, 952, no("try_join cancels upstream half; only lost connection reuse (performance)", "medium")),
    # ---------------- Databend ----------------
    (DB, 20044, v2("kernel_or_remote", "acquired_uncommitted", "unknown", "invariant", "no", "context",
                   "abort", "app", "review", "yes", "medium",
                   "data files visible before manifest; cancellation leaves partial dataset; " + AUDIT)),
    (DB, 17902, v2("shared_object", "acquired_uncommitted", "retry", "invariant", "no", "wrapper",
                   "timeout", "app", "review", "yes", "medium",
                   "timeout layer placed outside other layers cancelled their internal state")),
    (DB, 20042, v2("dropped_future", "committed_unowned", "unknown", "loss;leak", "no", "wrapper",
                   "abort", "app", "review", "yes", "medium",
                   "objects written before CommitMeta emitted; cancellation loses the metadata; " + AUDIT,
                   gh(DB, "pull", 20043))),
    (DB, 20043, dup(gh(DB, "issues", 20042), "related fix")),
    (DB, 20015, v2("dropped_future", "acquired_uncommitted", "retry", "loss", "no", "wrapper", "drop",
                   "app", "review", "yes", "high",
                   "spilled page removed from queue before restore await; retry cannot recover it",
                   gh(DB, "pull", 20016))),
    (DB, 20016, dup(gh(DB, "issues", 20015), "fix")),
    (DB, 20027, dup(gh(DB, "issues", 20015), "alternative fix (unmerged)")),
    (DB, 20020, v2("shared_object", "recorded_undelivered", "none", "invariant", "no",
                   "wrapper;context", "abort", "app", "review", "yes", "high",
                   "called_on_finish set before awaiting on_finish; cancel records unfinished work as done; "
                   + AUDIT, gh(DB, "pull", 20021))),
    (DB, 20021, dup(gh(DB, "issues", 20020), "fix")),
    # ---------------- Deno ----------------
    (DN, 20316, v2("dropped_future", "n/a", "none", "panic", "no", "other", "drop", "app", "failure",
                   "yes", "high", "request future dropped on TCP close while OpState lock held; drop panics")),
    (DN, 35601, v2("blocking_thread", "committed_unowned", "reuse", "loss", "yes", "context", "drop",
                   "app", "failure", "yes", "medium",
                   "orphaned cancelled stdin blocking read eats the first line (same shape as tokio#5535)")),
    (DN, 36786, unclear("node:http resends destroyed POST; cancellation is JS-level destroy()")),
    # ---------------- gRPC-Rust (tonic) ----------------
    (GR, 2791, v2("kernel_or_remote", "acquired_uncommitted", "none", "loss;invariant", "no", "other",
                  "drop", "library", "review", "unknown", "medium",
                  "dropped client stream ends with EOS (graceful) before RST; server may commit partial payload")),
    # ---------------- libp2p / linkerd / meilisearch / iroh ----------------
    (LP, 2329, v2("runtime", "n/a", "none", "loss", "no", "other", "abort", "library", "review",
                  "unknown", "medium", "aborted pending connection: error event silently dropped")),
    (LK, 299, v2("shared_object", "acquired_uncommitted", "none", "liveness", "no", "other", "drop",
                 "app", "failure", "yes", "medium",
                 "Dispatch future dropped but event sender now lives in Tap; tap stream never ends")),
    (LK, "767806bb2bc6", dup(gh(LK, "pull", 299), "commit")),
    (LK, 220, v2("other_task", "acquired_uncommitted", "none", "leak", "yes", "other", "drop", "app",
                 "failure", "yes", "medium",
                 "profile daemon future outlives dropped service; grpc streams accumulate")),
    (MS, 6513, v2("shared_object", "acquired_uncommitted", "retry", "corruption", "no", "context",
                  "shutdown", "app", "review", "yes", "medium",
                  "Ctrl-C mid-download leaves partial canonical cache file reused as valid; " + AUDIT)),
    (MS, 6508, v2("other_task", "acquired_uncommitted", "none", "collateral_failure;leak", "no",
                  "other", "drop", "app", "review", "yes", "medium",
                  "cancelled waiter's sender stays in search queue, consumes capacity; " + AUDIT,
                  gh(MS, "pull", 6521))),
    (MS, 6521, dup(gh(MS, "issues", 6508), "fix (open)")),
    (IR, 2572, v2("shared_object", "acquired_uncommitted", "retry", "corruption", "no",
                  "wrapper;context", "select", "app", "failure", "yes", "high",
                  "length-prefixed read in select! aborted mid-message; next read parses garbage length")),
    (IR, 2536, v2("runtime", "n/a", "retry", "liveness", "no", "other", "drop", "library", "failure",
                  "yes", "medium", "flume: cancelled recv_async loses notifications (bug in flume)")),
    (IR, 2533, dup(gh(IR, "pull", 2536), "same flume notification loss, shutdown hang")),
    (IR, 2924, v2("blocking_thread", "acquired_uncommitted", "none", "leak", "yes", "other", "drop",
                  "app", "failure", "yes", "high", "spawn_blocking in STUN handler not abortable; memory grows")),
    # ---------------- Neon ----------------
    (NE, 7117, v2("shared_object", "acquired_uncommitted", "reuse", "invariant", "no", "context", "drop",
                  "app", "failure", "yes", "medium",
                  "hyper cancels sql_over_http handler on connection close; pooled connection state")),
    (NE, 12345, v2("dropped_future", "acquired_uncommitted", "none", "liveness;collateral_failure", "no",
                   "wrapper", "drop", "app", "failure", "yes", "high",
                   "BatchQueue leader removes jobs then is cancelled; followers never get responses")),
    (NE, "517a3d0d8630", dup(gh(NE, "pull", 12345), "commit")),
    (NE, 3478, v2("shared_object", "acquired_uncommitted", "unknown", "invariant", "no", "context",
                  "drop", "app", "review", "yes", "high",
                  "management API handlers dropped on client hang-up; e.g. /detach half done")),
    (NE, 6028, v2("shared_object", "acquired_uncommitted", "reuse", "invariant", "no", "context",
                  "drop", "app", "failure", "yes", "medium",
                  "get_or_maybe_download cancelled after cancelling eviction: state vs filesystem mismatch")),
    (NE, 6101, v2("kernel_or_remote", "acquired_uncommitted", "none", "memory_safety", "yes", "wrapper",
                  "drop", "app", "review", "unknown", "high",
                  "read future dropped while io_uring read live: use-after-close of fd")),
    (NE, 10023, v2("shared_object", "acquired_uncommitted", "none", "invariant", "no", "wrapper", "drop",
                   "app", "review", "yes", "high", "throttle() cancel leaves metrics unbalanced (low impact)")),
    (NE, 5697, v2("dropped_future", "acquired_uncommitted", "shutdown", "loss", "no", "wrapper",
                  "shutdown", "app", "failure", "yes", "medium", "flush op dropped when ListWriter cancelled")),
    (NE, 7235, v2("other_task", "acquired_uncommitted", "shutdown", "leak;effect_after_close", "yes",
                  "wrapper", "select", "app", "failure", "yes", "high",
                  "drop_old_connection not cancel safe; walreceiver task dangles after Timeline::shutdown")),
    (NE, 5696, unclear("page_service hang on cancel; mechanism not stated", "medium")),
    (NE, "2bd79906d944", unclear("commit of #5696", "medium")),
    (NE, 4146, no("hypothetical future brittleness", "medium")),
    # ---------------- Polkadot / Qdrant ----------------
    (PK, 11013, v2("dropped_future", "acquired_uncommitted", "retry", "loss", "no", "context", "drop",
                   "app", "failure", "yes", "medium",
                   "response future dropped on peer disconnect; justification response lost (#5414)")),
    (QD, 9665, v2("dropped_future", "acquired_uncommitted", "reuse", "loss;invariant", "no",
                  "wrapper;context", "drop", "app", "review", "yes", "medium",
                  "local.take() then await; cancellation drops the shard and leaves slot None; " + AUDIT)),
    (QD, 9666, dup(gh(QD, "issues", 9665), "fix (unmerged)")),
    (QD, 9667, dup(gh(QD, "issues", 9665), "fix (unmerged)")),
    (QD, 9745, v2("dropped_future", "acquired_uncommitted", "reuse", "invariant", "no", "wrapper;context",
                  "timeout", "app", "review", "yes", "medium",
                  "init_empty_local_shard: local.take() then awaits under grpc-timeout; " + AUDIT)),
    (QD, 9770, dup(gh(QD, "issues", 9745), "fix (open)")),
    (QD, 9670, v2("shared_object", "acquired_uncommitted", "reuse", "liveness;invariant", "no", "context",
                  "other", "app", "review", "yes", "high",
                  "try_join_all drops sibling restart futures after workers stopped (fail-fast combinator)",
                  gh(QD, "pull", 9671))),
    (QD, 9671, dup(gh(QD, "issues", 9670), "fix")),
    (QD, 3367, v2("shared_object", "acquired_uncommitted", "unknown", "invariant", "no", "context", "drop",
                  "app", "review", "yes", "medium",
                  "update API dropped on client disconnect could break local invariants / node consistency")),
    (QD, 9532, v2("kernel_or_remote", "committed_unowned", "none", "leak", "no", "wrapper", "drop", "app",
                  "review", "yes", "medium",
                  "snapshot persisted before cleanup guard registered; cancel leaves it behind; " + AUDIT)),
    (QD, 9533, dup(gh(QD, "issues", 9532), "fix (open)")),
    (QD, 7530, v2("blocking_thread", "before_acquire", "none", "leak;liveness", "yes", "other", "timeout",
                  "app", "failure", "yes", "high",
                  "queued spawn_blocking search tasks still run after the search future is dropped")),
    (QD, 7533, dup(gh(QD, "pull", 7530), "same fix applied to all spawn_blocking sites")),
    (QD, 10338, v2("shared_object", "acquired_uncommitted", "none", "collateral_failure", "no", "other",
                   "timeout", "app", "review", "yes", "medium",
                   "one waiter's timeout removed shared broadcast entry; other waiters fail")),
    (QD, 8680, v2("other_task", "acquired_uncommitted", "none", "liveness", "yes", "other", "timeout",
                  "app", "failure", "yes", "high",
                  "caller timed out but update worker keeps waiting; head-of-line blocking")),
    (QD, 9668, adjacent("cooperative token cancellation leaves durable dirty marker (future not dropped)")),
    (QD, 9686, adjacent("fix for #9668")),
    (QD, 9773, adjacent("fix for #9668 (unmerged)")),
    (QD, 9217, adjacent("cooperative (stopped flag) optimisation cancel leaks segment dir")),
    (QD, 7787, unclear("aborted transfer leaves bumped clocks; abort mechanism not stated", "medium")),
    # ---------------- Redis ----------------
    (RD, 325, v2("shared_object", "acquired_uncommitted", "reuse", "mismatch", "no", "context", "timeout",
                 "library", "review", "yes", "medium",
                 "interrupted query leaves reply on the connection; next command reads it",
                 gh(RD, "pull", 733))),
    (RD, 733, dup(gh(RD, "issues", 325), "mitigation: mark aborted connections (unmerged)")),
    (RD, 553, unclear("select! with xread leaves 'dangling connection'; details unclear", "medium")),
    (RD, 851, unclear("select! with MultiplexedConnection odd behaviour", "low")),
    # ---------------- RisingWave ----------------
    (RW, 12725, v2("dropped_future", "acquired_uncommitted", "retry", "loss", "no", "wrapper", "select",
                   "app", "review", "yes", "high",
                   "kv log store next_item dropped in select! with delivery future; flushed item lost")),
    (RW, 12744, dup(gh(RW, "pull", 12725), "backport")),
    (RW, 26176, v2("kernel_or_remote", "acquired_uncommitted", "none", "leak;invariant", "no", "wrapper",
                   "drop", "app", "review", "yes", "medium",
                   "txn label take() then await commit; cancel loses rollback owner of external txn; " + AUDIT)),
    (RW, 26180, v2("dropped_future", "acquired_uncommitted", "retry", "invariant", "no", "wrapper", "drop",
                   "app", "review", "yes", "medium",
                   "inserter.take() then await end(); cancel loses finalization owner before truncation; "
                   + AUDIT)),
    (RW, 26179, v2("dropped_future", "committed_unowned", "none", "loss;invariant", "no", "wrapper",
                   "drop", "app", "review", "yes", "medium",
                   "delivery future lost if cancelled while waiting for manager capacity; " + AUDIT)),
    (RW, 26172, v2("kernel_or_remote", "committed_unowned", "none", "leak", "no", "wrapper", "drop", "app",
                   "review", "yes", "medium",
                   "S3 multipart upload started; abort only on finish() error path; drop leaks it; " + AUDIT)),
    (RW, 6985, v2("shared_object", "acquired_uncommitted", "none", "panic;invariant", "no", "context",
                  "drop", "app", "failure", "yes", "high",
                  "merge iterator next() dropped holding PeekMut; drop compares inconsistent iterators")),
    (RW, 6324, dup(gh(RW, "pull", 6985), "earlier fix of the same PeekMut-on-drop class (sstable iter)")),
    (RW, 22128, v2("shared_object", "acquired_uncommitted", "reuse", "loss", "no", "context", "drop",
                   "app", "failure", "yes", "high",
                   "mysql_async exec_drop dropped mid-run; reused connection returns empty stream")),
    (RW, 26409, v2("shared_object", "acquired_uncommitted", "retry", "panic", "no", "context", "select",
                   "app", "failure", "yes", "high",
                   "no-op ALTER SINK cancels consumer in select!; restart without rewinding log reader panics",
                   gh(RW, "pull", 26412))),
    (RW, 26412, dup(gh(RW, "issues", 26409), "fix")),
    (RW, 26483, dup(gh(RW, "issues", 26409), "same no-op cancellation, recovery variant")),
    (RW, 3909, v2("dropped_future", "acquired_uncommitted", "none", "liveness;collateral_failure", "no",
                  "wrapper", "drop", "app", "failure", "yes", "high",
                  "LRU dedup: first caller fetches, others wait; dropping it strands them",
                  gh(RW, "pull", 3911))),
    (RW, 3911, dup(gh(RW, "issues", 3909), "fix")),
    (RW, 26220, v2("runtime", "n/a", "shutdown", "panic", "no", "other", "shutdown", "app", "failure",
                   "yes", "medium", "timer task panics when child loop cancelled at shutdown")),
    # ---------------- Vector ----------------
    (VE, 24670, v2("dropped_future", "delivered_unrecorded", "shutdown", "duplication", "no", "context",
                   "select", "app", "review", "yes", "medium",
                   "select! cancels run_once after events sent, before SQS delete: duplicate delivery")),
    (VE, 23097, no("'Source send cancelled.' is expected when agent drops connection; client resends")),
    (VE, 20305, no("same as #23097")),
]
